name: xoxno_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

dependencies:
  chopper: ^8.0.1+1
  clock: ^1.1.1
  dart_jsonwebtoken: ^2.14.0
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.11
  chopper_generator: ^8.0.1
  json_serializable: ^6.8.0
  lints: ^4.0.0
  swagger_dart_code_generator: ^3.0.0
  test: ^1.25.8
