name: xoxno_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

dependencies:
  intl: ^0.20.2
  chopper: ^8.1.0
  clock: ^1.1.2
  dart_jsonwebtoken: ^3.2.0
  http: ^1.4.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  mime: any

dev_dependencies:
  build_runner: ^2.5.3
  chopper_generator: ^8.1.0
  json_serializable: any
  lints: any
  swagger_dart_code_generator: ^3.0.3
  test: ^1.26.2
