name: xoxno_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

dependencies:
  chopper: ^6.1.1
  clock: ^1.1.1
  dart_jsonwebtoken: ^2.14.0
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.11
  chopper_generator: ^6.0.0
  json_serializable: ^6.8.0
  lints: ^3.0.0
  swagger_dart_code_generator: ^2.10.4
  test: ^1.24.0
